services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./mongo:/data/db
    healthcheck:
      test: mongosh -u $MONGO_USER -p $MONGO_PASSWORD --authenticationDatabase admin --quiet --eval "db.adminCommand('ping').ok"
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - 27017:27017

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - 5432:5432

  mongo-express:
    image: mongo-express:latest
    restart: always
    env_file: .env
    depends_on:
      - mongodb
    ports:
      - 8081:8081

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
