services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./mongo:/data/db
    healthcheck:
      test: mongosh -u $MONGO_USER -p $MONGO_PASSWORD --authenticationDatabase admin --quiet --eval "db.adminCommand('ping').ok"
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - web

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - web

  api:
    container_name: api
    build:
      context: ./questbot_api
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      mongodb:
        condition: service_healthy
        restart: true
    env_file: .env
    healthcheck:
      test: curl -f api:3000
      timeout: 3s
      interval: 10s
      retries: 5
    networks:
      - web
    ports:
      - 9933:3000

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: ./questbot/Dockerfile
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
        restart: true
    env_file: .env
    networks:
      - web

  ui:
    container_name: ui
    build:
      context: ./questbot_ui
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
        restart: true
    env_file: .env
    ports:
      - 9900:9900
    networks: 
      - web

volumes:
  questbot_db:

networks:
  web:
    driver: bridge
