services:
  postgres:
    image: postgres
    restart: always
    env_file: .env

  api:
    build:
      context: ./questbot_api
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - postgres
    env_file: .env

  questbot:
    build:
      context: .
      dockerfile: ./questbot/Dockerfile
    restart: always
    depends_on:
      - api
    env_file: .env

  ui:
    build:
      context: ./questbot_ui
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - api
    env_file: .env
    ports:
      - 9900:80
